/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Insurance.InsurancePlan;
import Model.Business;
import javax.swing.JOptionPane;

/**
 *
 * @author caofei
 */
public class AddInsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddInsuranceJPanel
     */
     private Business business;
    public AddInsuranceJPanel() {
        initComponents();
    }

    AddInsuranceJPanel(Business business) {
        initComponents();
        this.business=business;
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planIdfield = new javax.swing.JTextField();
        planNamefield = new javax.swing.JTextField();
        planCostfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(planIdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, 30));
        add(planNamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 30));
        add(planCostfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("ADD INSURANCE PLAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel3.setText("NAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel4.setText("COST PER MONTH");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
     
        InsurancePlan plan=this.business.getInsPlan();
         String id = planIdfield.getText();
         String name = planNamefield.getText();
         String cost = planCostfield.getText();
         
         plan.createPlandetail(Integer.valueOf(id), name, Integer.valueOf(cost));
         JOptionPane.showMessageDialog(null, "Added successfully");
        
        
    }//GEN-LAST:event_AddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField planCostfield;
    private javax.swing.JTextField planIdfield;
    private javax.swing.JTextField planNamefield;
    // End of variables declaration//GEN-END:variables
}
