/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Applicant.Applicant;
import Applicant.Pet;
import Applicant.Vaccine;
import Model.Business;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caofei
 */
public class AddVacineJPanel extends javax.swing.JPanel {

   private Business business;
    DefaultTableModel PetTableModel;
    DefaultTableModel VaccineTableModel;
    Pet selectedPet;
    private Boolean vVaccine = true;
    private Boolean vCoursed = true;
    public AddVacineJPanel() {
        initComponents();
    }
    AddVacineJPanel(Business business) {
        initComponents();
        this.business = business;
        this.PetTableModel = (DefaultTableModel) PetTable.getModel();
        this.VaccineTableModel = (DefaultTableModel) VaccineTable.getModel();
        displayPet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        VaccineTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fieldVaccine = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PetTable = new javax.swing.JTable();
        selectBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VaccineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine", "isCoursed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VaccineTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 430, 190));

        jLabel1.setText("vaccine");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        fieldVaccine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldVaccineFocusLost(evt);
            }
        });
        add(fieldVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 130, -1));

        jLabel9.setText("isCoursed");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 70, 40));

        buttonGroup1.add(jRadioButtonYes);
        jRadioButtonYes.setText("yes");
        add(jRadioButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setText("no");
        add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        PetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "petName", "petType", "master", "vaccine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PetTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 400, 340));

        selectBtn.setText("SELECT");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldVaccineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldVaccineFocusLost
        // TODO add your handling code here:
        String name = fieldVaccine.getText();
        Boolean isUnique = this.selectedPet.checkIfVaccineUnique(name);
        if(!isUnique) {
            fieldVaccine.setText("");
            JOptionPane.showMessageDialog(null, "Vaccine already exists.", "warning", JOptionPane.WARNING_MESSAGE);
        }
        String detect = fieldVaccine.getText();
        this.vVaccine = detect.isEmpty();
    }//GEN-LAST:event_fieldVaccineFocusLost

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonYes.isSelected() || jRadioButtonNo.isSelected()) {
            vCoursed = false;
        }
        if (vVaccine || vCoursed) {
            JOptionPane.showMessageDialog(null, "Pleae fill all vaccine information", "warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String name = fieldVaccine.getText();
            String coursed = "false";
            if(jRadioButtonYes.isSelected()){
                coursed = "true";
            }
            this.selectedPet.createVaccine(name, Boolean.valueOf(coursed));
            displayPet();
            displayVaccine(this.selectedPet.getVaccineList());
            fieldVaccine.setText("");
            buttonGroup1.clearSelection();
            vVaccine = vCoursed = true;
            JOptionPane.showMessageDialog(null, "Saved!");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = PetTable.getSelectedRow();
        if(selectedRow >= 0) {
            String id = (String) PetTable.getValueAt(selectedRow, 0);
            String name = (String) PetTable.getValueAt(selectedRow, 1);
            this.selectedPet = (Pet) this.business.getAppDirectory().findApplicant(id).getPet();
            displayVaccine(selectedPet.getVaccineList());
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    public void displayPet() {
        PetTableModel.setRowCount(0);
        for(Applicant applicant: this.business.getAppDirectory().getApplicantlist()) {
            Object[] row = new Object[5];
            row[0] = applicant.getApplicationID();
            row[1] = applicant.getPet().getPetName();
            row[2] = applicant.getPet().getPetType();
            row[3] = (applicant.getOwnerFirstname()+" "+applicant.getOwnerLastName());
            if(applicant.getPet().getVaccineList().size() > 0) {
                row[4] = "collected";
            } else {
                row[4] = "N/A";
            }
            PetTableModel.addRow(row);
            
        }
    }
    public void displayVaccine(ArrayList<Vaccine> vaccineList) {
        if(vaccineList.size() > 0) {
            VaccineTableModel.setRowCount(0);
            for(Vaccine vac: vaccineList) {
                Object row[] = new Object[2];
                row[0] = vac.getVaccineName();
                row[1] = "no";
                if(vac.isCompleted()){
                    row[1] = "yes";
                }
                VaccineTableModel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PetTable;
    private javax.swing.JTable VaccineTable;
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldVaccine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
