/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Applicant.Applicant;
import Applicant.ApplicantDirectory;
import Model.Business;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author caofei
 */
public class CreatApplicantJPanel extends javax.swing.JPanel {

    private Business business;
    DefaultTableModel appTableModel;
    
    
    public CreatApplicantJPanel() {
        initComponents();
    }
    CreatApplicantJPanel(Business business) {
        initComponents();
        this.business = business;
        this.appTableModel = (DefaultTableModel) applicantCatalog.getModel();
        SimpleDateFormat sdf=new SimpleDateFormat("MM/dd/yyyy",Locale.ENGLISH);
        displayMedicineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        applicantCatalog = new javax.swing.JTable();
        fieldLastName = new javax.swing.JTextField();
        fieldId = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        fieldFirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        applicantCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "FirstName", "LastName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(applicantCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 410, 430));
        add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, 40));

        fieldId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldIdFocusLost(evt);
            }
        });
        add(fieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, 40));

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 110, 40));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));
        add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 40));

        jLabel1.setText("Last Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("First Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("CREATE NEW  APPLICANT");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldIdFocusLost
        // TODO add your handling code here:
        String id = fieldId.getText();
        Boolean isUnique=this.business.getAppDirectory().checkIfApplicantUnique(id);
        if(isUnique) {

        } else {
            fieldId.setText("");
            JOptionPane.showMessageDialog(null, "Applicant already exists");
        }
    }//GEN-LAST:event_fieldIdFocusLost

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
          
            
        int selectedRow = applicantCatalog.getSelectedRow();
        if(selectedRow >= 0) {
            Applicant a = (Applicant) applicantCatalog.getValueAt(selectedRow, 0);
            this.business.getAppDirectory().removeApplicant(a.getApplicationID());
            displayMedicineCatalog();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String id = fieldId.getText();
        String fname = fieldFirstName.getText();
        String lname = fieldLastName.getText();
 
        
        ApplicantDirectory directory = this.business.getAppDirectory();
        directory.createApplicant(id, fname, lname);
        displayMedicineCatalog();
    }//GEN-LAST:event_addBtnActionPerformed
  public void displayMedicineCatalog() {
        ArrayList<Applicant> applicant = this.business.getAppDirectory().getApplicantlist();
        
        if(applicant.size() > 0) {
            appTableModel.setRowCount(0);
            for(Applicant a: applicant) {
                Object row[] = new Object[3];
                row[0] = a;
                row[1] = a.getOwnerFirstname();
                row[2] = a.getOwnerLastName();
                appTableModel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable applicantCatalog;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
