/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Applicant.Applicant;
import Applicant.Pet;
import Insurance.PlanDetail;
import Model.Business;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caofei
 */
public class InsuranceAssignJPanel extends javax.swing.JPanel {

    private Business business;
    DefaultTableModel AssignTableModel;
    public InsuranceAssignJPanel() {
        initComponents();
    }
     InsuranceAssignJPanel(Business business) {
        initComponents();
        this.business = business;
        this.AssignTableModel = (DefaultTableModel) AssignTable.getModel();
        display();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignTable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        assignBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 110, 60));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("ASSIGN");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel9.setText("Applicant's plan");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));

        AssignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "petName", "petType", "master", "Insurance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AssignTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 150, -1));

        assignBtn.setText("ASSIGN");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        PlanDetail plan = (PlanDetail) this.business.getInsPlan().findObservation((Integer) jComboBox1.getSelectedItem());
        int selectedRow = AssignTable.getSelectedRow();
        String id = (String) AssignTable.getValueAt(selectedRow, 0);
        String name = (String) AssignTable.getValueAt(selectedRow, 1);
        Pet pet = (Pet) this.business.getAppDirectory().findApplicant(id).getPet();
        pet.setPlan(plan.getPlanName());
        display();
    }//GEN-LAST:event_assignBtnActionPerformed
   
    
public void display() {
        AssignTableModel.setRowCount(0);
        for(Applicant applicant: this.business.getAppDirectory().getApplicantlist()) {
           
                Object[] row = new Object[5];
                row[0] = applicant.getApplicationID();
                row[1] = applicant.getPet().getPetName();
                row[2] = applicant.getPet().getPetType();
                row[3] = (applicant.getOwnerFirstname()+" "+applicant.getOwnerLastName());
                row[4] = applicant.getPet().getPlan();
                AssignTableModel.addRow(row);
            }
        }
    
public void populate() {
        jComboBox1.removeAllItems();
        for(PlanDetail plan: this.business.getInsPlan().getPlanlist()) {
            jComboBox1.addItem(plan.getPlanID());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AssignTable;
    private javax.swing.JButton assignBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
