/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Insurance.InsurancePlan;
import Insurance.PlanDetail;
import Model.Business;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caofei
 */
public class ViewInsuranceJPanel extends javax.swing.JPanel {

    private Business business;
    DefaultTableModel viewtableModel;
    PlanDetail selectedPlan;
    public ViewInsuranceJPanel() {
        initComponents();
    }

    ViewInsuranceJPanel(Business business) {
        initComponents();
        
        this.viewtableModel = (DefaultTableModel) observationTable.getModel();
        this.business = business;
        displayplanDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planIdfield = new javax.swing.JTextField();
        planNamefield = new javax.swing.JTextField();
        planCostfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observationTable = new javax.swing.JTable();
        updateObservationbtn = new javax.swing.JButton();
        viewObservationbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        planIdfield.setEnabled(false);
        planIdfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planIdfieldActionPerformed(evt);
            }
        });
        add(planIdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 30));
        add(planNamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));
        add(planCostfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("VIEW INSURANCE PLAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel2.setText("PLAN ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setText("PLAN NAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel4.setText("COST PER MONTH");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        observationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Temperature", "Cost per month"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(observationTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 440, 410));

        updateObservationbtn.setText("UPDATE OBSERVATION");
        updateObservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateObservationbtnActionPerformed(evt);
            }
        });
        add(updateObservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 150, 40));

        viewObservationbtn.setText("VIEW DETAILS");
        viewObservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewObservationbtnActionPerformed(evt);
            }
        });
        add(viewObservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 190, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void updateObservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateObservationbtnActionPerformed
        // TODO add your handling code here:
        if(!planIdfield.getText().isEmpty()) {
            PlanDetail o = this.business.getInsPlan().findObservation(Integer.valueOf(planIdfield.getText()));
            o.setPlanName(String.valueOf(planNamefield.getText()));
            o.setCostperMonth(Integer.valueOf(planCostfield.getText()));
            
            JOptionPane.showMessageDialog(null, "Updated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "You have not made any selection");
        }
        
    }//GEN-LAST:event_updateObservationbtnActionPerformed

    private void viewObservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewObservationbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = observationTable.getSelectedRow();
        if(selectedRow >= 0) {
            this.selectedPlan = (PlanDetail) observationTable.getValueAt(selectedRow, 0);
            

            planIdfield.setText(String.valueOf(selectedPlan.getPlanID()));
            planNamefield.setText(String.valueOf(selectedPlan.getPlanName()));
            planCostfield.setText(String.valueOf(selectedPlan.getCostperMonth()));
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_viewObservationbtnActionPerformed

    private void planIdfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planIdfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planIdfieldActionPerformed
     public void displayplanDetail() {
        InsurancePlan plan = this.business.getInsPlan();
        
        if(plan.getInsurancePlan().size() > 0) {//如果这个数列不是0 的话
            viewtableModel.setRowCount(0);
            for(PlanDetail o: plan.getInsurancePlan()) {
                Object row[] = new Object[3];
                row[0] = o;
                row[1] = o.getPlanName();
                row[2] = o.getCostperMonth();
                
                viewtableModel.addRow(row);
            }
        } else {
            System.out.println("Empty list");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable observationTable;
    private javax.swing.JTextField planCostfield;
    private javax.swing.JTextField planIdfield;
    private javax.swing.JTextField planNamefield;
    private javax.swing.JButton updateObservationbtn;
    private javax.swing.JButton viewObservationbtn;
    // End of variables declaration//GEN-END:variables
}
