/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CustomerPanels;

import Business.Branch;
import Business.Business;
import Customer.Customer;
import Library.Book;
import Library.Magazine;
import Rental.Rental;
import Rental.RentalDirectory;

import UI.MainJFrame;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caofei
 */
public class CustomerJFrame extends javax.swing.JFrame {

    private Business business;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel appTableModel;
    DefaultTableModel appTableModel1;
    Book selectbook;

    /**
     * Creates new form CustomerJFrame
     */
    public CustomerJFrame() {
        initComponents();
    }

    public CustomerJFrame(Business business, Branch branch, UserAccount useraccount) {
       initComponents();
       this.setVisible(true);
       this.appTableModel = (DefaultTableModel) applicantCatalog.getModel();
       this.business = business;
       this.branch = branch;
       this.useraccount = useraccount;
       this.appTableModel = (DefaultTableModel) applicantCatalog.getModel();
       this.appTableModel1 = (DefaultTableModel) applicantCatalog1.getModel();
       
       displayBookCatalog();
       displayMagazineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BorrowBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        applicantCatalog = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        applicantCatalog1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BorrowBtn1 = new javax.swing.JButton();
        BorrowBtn2 = new javax.swing.JButton();
        BorrowBtn3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));

        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(757, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jSplitPane1.setTopComponent(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 153, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BorrowBtn.setText("Borrow");
        BorrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBtnActionPerformed(evt);
            }
        });
        jPanel5.add(BorrowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 120, 40));

        applicantCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Author", "Genre", "No of Page", "Language", "SerialNum", "Registered Date", "Staus", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(applicantCatalog);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 200));

        applicantCatalog1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Company Name", "Issue type", "SerialNum", "Registered Date", "Staus", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(applicantCatalog1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 610, 200));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("Book");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 60, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Magazine");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 120, 30));

        BorrowBtn1.setText("Borrow");
        BorrowBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(BorrowBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 120, 40));

        BorrowBtn2.setText("Return");
        BorrowBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBtn2ActionPerformed(evt);
            }
        });
        jPanel5.add(BorrowBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 120, 40));

        BorrowBtn3.setText("Return");
        BorrowBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBtn3ActionPerformed(evt);
            }
        });
        jPanel5.add(BorrowBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 120, 40));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 130, 30));

        jLabel2.setText("Duration");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 130, 30));

        jLabel3.setText("Duration");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, -1));

        jSplitPane1.setRightComponent(jPanel5);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(business, branch, useraccount);
    }//GEN-LAST:event_backBtnActionPerformed

    private void BorrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBtnActionPerformed

        int selectedrow = applicantCatalog1.getSelectedRow();//在其中的表中找到相应的行
        Magazine b=(Magazine)applicantCatalog1.getValueAt(selectedrow, 0);
        
        Rental r=new Rental();
        r.setMagazine(b);
        r.setCustomerId(this.useraccount.getAccountId());
        r.setStatus("want apply");
        r.setRentalDuration(jTextField2.getText());
        r.setBranchName(this.branch.getName());
        b.setDuration(jTextField2.getText());
        b.setStatus("want apply");
        
        
        RentalDirectory rd=branch.getRentalrequest();
        rd.getRentallist().add(r);
        
        RentalDirectory rdd=this.business.getAllRentalDirectory();
        rdd.getRentallist().add(r);
        displayBookCatalog();
    }//GEN-LAST:event_BorrowBtnActionPerformed

    private void BorrowBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBtn1ActionPerformed
        // TODO add your handling code here:
        int selectedrow = applicantCatalog.getSelectedRow();//在其中的表中找到相应的行
        Book b=(Book)applicantCatalog.getValueAt(selectedrow, 0);
        
        Rental r=new Rental();
        r.setBook(b);
        r.setCustomerId(this.useraccount.getAccountId());
        r.setStatus("want apply");
        r.setRentalDuration(jTextField1.getText());
        b.setStatus("want apply");
        b.setDuration(jTextField1.getText());
        r.setBranchName(this.branch.getName());
        
        RentalDirectory rd=branch.getRentalrequest();
        rd.getRentallist().add(r);
        
        RentalDirectory rdd=this.business.getAllRentalDirectory();
        rdd.getRentallist().add(r);
        displayBookCatalog();
        
        
    }//GEN-LAST:event_BorrowBtn1ActionPerformed

    private void BorrowBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBtn2ActionPerformed
        // TODO add your handling code here:
        int selectedrow = applicantCatalog.getSelectedRow(); 
        Book b=(Book)applicantCatalog.getValueAt(selectedrow, 0);

        Rental r=this.branch.getRentalrequest().findByBook(b);

        r.setStatus("Returned");
        b.setStatus("Returned");
        b.setDuration("");

        displayBookCatalog();
    }//GEN-LAST:event_BorrowBtn2ActionPerformed

    private void BorrowBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBtn3ActionPerformed
        // TODO add your handling code here:
        int selectedrow = applicantCatalog1.getSelectedRow();
        Book b=(Book)applicantCatalog1.getValueAt(selectedrow, 0);

        Rental r=this.branch.getRentalrequest().findByBook(b);

        r.setStatus("Returned");
        b.setStatus("Returned");
        b.setDuration("");

        displayBookCatalog();
    }//GEN-LAST:event_BorrowBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerJFrame().setVisible(true);
            }
        });
    }
public void displayBookCatalog() {
        ArrayList<Book> booklist = this.branch.getLibrary().getBookdirectory().getBooklist();
        
        if(booklist.size() > 0) {
            appTableModel.setRowCount(0);
            for(Book a: booklist) {
                Object row[] = new Object[9];
                row[0] = a;
                row[1] = a.getAuthor();
                row[2] = a.getGenre();
                row[3] = a.getNoofpage();
                row[4] = a.getLanguage();
                row[5] = a.getSerialnum();
                row[6] = a.getDate();
                row[7] = a.getStatus();
                row[8] = a.getDuration();
                appTableModel.addRow(row);
            }
        }
    }
 public void displayMagazineCatalog() {
        ArrayList<Magazine> magazinelist = this.branch.getLibrary().getMagazineDirectory().getMagazinelist();
        
        if(magazinelist.size() > 0) {
            appTableModel1.setRowCount(0);
            for(Magazine a: magazinelist) {
                Object row[] = new Object[7];
                row[0] = a;
            
                row[1] = a.getComname();
                row[2] = a.getIssuetype();
                row[3] = a.getSerialnum();
                row[4] = a.getDate();
                row[5] = a.getStatus();
                row[6] = a.getDuration();
                appTableModel1.addRow(row);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrowBtn;
    private javax.swing.JButton BorrowBtn1;
    private javax.swing.JButton BorrowBtn2;
    private javax.swing.JButton BorrowBtn3;
    private javax.swing.JTable applicantCatalog;
    private javax.swing.JTable applicantCatalog1;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
