/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab_cao2;

import Model.Person;
import Model.Contact;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author caofei
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Contact delPackage;
    
    private Boolean validate = true;
    private Boolean pvalidate = true;
    private Boolean avalidate = true;
    private Boolean bvalidate = true;
    private Boolean cvalidate = true;
    private Boolean dvalidate = true;
    private Boolean evalidate = true;
    private Boolean fvalidate = true;
    private Boolean gvalidate = true;
    private Boolean hvalidate = true;
    private Boolean ivalidate = true;
    private Boolean jvalidate = true;
    public CreateJPanel() {
        initComponents();
    }
    CreateJPanel(Contact deliveryPackage) {
        initComponents();

        this.delPackage = deliveryPackage;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        saveProductbtn = new javax.swing.JButton();
        fieldFname = new javax.swing.JTextField();
        fieldLname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldUname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fieldrecT = new javax.swing.JTextField();
        fieldnoS = new javax.swing.JTextField();
        fieldigF = new javax.swing.JTextField();
        fielddL = new javax.swing.JTextField();
        fieldnoI = new javax.swing.JTextField();
        fieldcoF = new javax.swing.JTextField();
        fielddeS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fieldpersonPhone = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fieldpersonEmail = new javax.swing.JTextField();
        jLabelImage = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonBrowseImage = new javax.swing.JButton();
        recipePath = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        saveProductbtn.setText("Save Product");
        saveProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductbtnActionPerformed(evt);
            }
        });
        add(saveProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 140, 30));

        fieldFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldFnameFocusLost(evt);
            }
        });
        add(fieldFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, -1));

        fieldLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldLnameFocusLost(evt);
            }
        });
        add(fieldLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 110, -1));

        jLabel8.setText("Username - Unique");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        fieldUname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUnameFocusLost(evt);
            }
        });
        add(fieldUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, -1));

        jLabel9.setText("Chef’s First Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel10.setText("Chef’s Last Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel17.setText("Recipe ");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel11.setText("Recipe title");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel12.setText("No. of Servings");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel13.setText("Is Gluten Free ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel14.setText("Difficulty level ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel15.setText("No. of Ingredients");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jLabel16.setText("Category of food");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        jLabel18.setText("Description");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        fieldrecT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldrecTFocusLost(evt);
            }
        });
        add(fieldrecT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 90, -1));

        fieldnoS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldnoSFocusLost(evt);
            }
        });
        add(fieldnoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, -1));

        fieldigF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldigFFocusLost(evt);
            }
        });
        add(fieldigF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 90, -1));

        fielddL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fielddLFocusLost(evt);
            }
        });
        fielddL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fielddLActionPerformed(evt);
            }
        });
        add(fielddL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 90, -1));

        fieldnoI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldnoIFocusLost(evt);
            }
        });
        fieldnoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnoIActionPerformed(evt);
            }
        });
        add(fieldnoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 100, -1));

        fieldcoF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldcoFFocusLost(evt);
            }
        });
        add(fieldcoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 100, -1));

        fielddeS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fielddeSFocusLost(evt);
            }
        });
        add(fielddeS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 100, -1));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel19.setText("Contact");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 90, -1));

        jLabel20.setText("person phone");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, -1));

        fieldpersonPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldpersonPhoneFocusLost(evt);
            }
        });
        add(fieldpersonPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, -1));

        jLabel21.setText("person email");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, -1));

        fieldpersonEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldpersonEmailFocusLost(evt);
            }
        });
        add(fieldpersonEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 90, -1));
        add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 150, 160));

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel22.setText("Picture");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jButtonBrowseImage.setText("Browser");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        add(jButtonBrowseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));
        add(recipePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 523, -1, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String check = "^([a-z0-9A-Z]+[-|\\.]?)+[a-z0-9A-Z]@([a-z0-9A-Z]+(-[a-z0-9A-Z]+)?\\.)+[a-zA-Z]{2,}$";  
        Pattern regex = Pattern.compile(check);  
        Matcher matcher = regex.matcher(fieldpersonEmail.getText());  
        boolean isMatched = matcher.matches();  
        System.out.println(isMatched);
     
     
     if(validate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(pvalidate) {
            JOptionPane.showMessageDialog(null,"Pleae fill all fields");
        } else if(avalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(bvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(cvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        }  else if(isMatched==false) {
            JOptionPane.showMessageDialog(null, "Please enter your vaild email");
        }   else {
            JOptionPane.showMessageDialog(null, "Added product!");
        }
        
     
     
       
        String phone=fieldpersonPhone.getText();
        String email=fieldpersonEmail.getText();
       
        String fName=fieldFname.getText();
        String lName=fieldLname.getText();
        String nName=fieldUname.getText();

        
        this.delPackage.setPhoneNumber(Long.valueOf(phone));
        this.delPackage.setEmailID(email);

        Person customer = this.delPackage.getCustomer();
        
        customer.setfName(fName);
        customer.setlName(lName);
        customer.setuName(nName);

        

    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductbtnActionPerformed
        if(dvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(evalidate) {
            JOptionPane.showMessageDialog(null,"Pleae fill all fields");
        } else if(fvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(gvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(hvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        }  else if(ivalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else if(jvalidate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else {
            JOptionPane.showMessageDialog(null, "Added product!");
        }
        
        String recT=fieldrecT.getText();
        String noS=fieldnoS.getText();
        String igF=fieldigF.getText();
        String dL=fielddL.getText();
        String noI=fieldnoI.getText();
        String coF=fieldcoF.getText();
        String deS=fielddeS.getText();
        
        
        Recipe product = this.delPackage.createRecipe(recT,Float.valueOf(noS),igF,Double.valueOf(dL),Integer.valueOf(noI),coF,deS);


    }//GEN-LAST:event_saveProductbtnActionPerformed

    private void fieldpersonEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldpersonEmailFocusLost
        // TODO add your handling code here:
        String name = fieldpersonEmail.getText();
        
        if(name.isEmpty()) {
            this.validate = true;
        } else {
            this.validate = false;
        }
        
       

    }//GEN-LAST:event_fieldpersonEmailFocusLost

    private void fieldnoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnoIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldnoIActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile=new JFileChooser();

        FileNameExtensionFilter fnef=new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue=browseImageFile.showOpenDialog(null);

        if(showOpenDialogue==JFileChooser.APPROVE_OPTION){
            File selectedImageFile=browseImageFile.getSelectedFile();
            String selectedImagePath=selectedImageFile.getAbsolutePath();
            recipePath.setText(selectedImagePath);

            ImageIcon ii=new ImageIcon(selectedImagePath);
            Image image=ii.getImage().getScaledInstance(jLabelImage.getWidth(),jLabelImage.getHeight(),Image.SCALE_SMOOTH);
            jLabelImage.setIcon(new ImageIcon(image));

        }
    }//GEN-LAST:event_jButtonBrowseImageActionPerformed

    private void fieldFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFnameFocusLost
        // TODO add your handling code here:
        String name = fieldFname.getText();
        
        if(name.isEmpty()) {
            this.pvalidate = true;
        } else {
            this.pvalidate = false;
        }
    }//GEN-LAST:event_fieldFnameFocusLost

    private void fieldLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldLnameFocusLost
        // TODO add your handling code here:
         String name = fieldLname.getText();
        
        if(name.isEmpty()) {
            this.avalidate = true;
        } else {
            this.avalidate = false;
        }
    }//GEN-LAST:event_fieldLnameFocusLost

    private void fieldUnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUnameFocusLost
        // TODO add your handling code here:
         String name = fieldUname.getText();
        
        if(name.isEmpty()) {
            this.bvalidate = true;
        } else {
            this.bvalidate = false;
        }
    }//GEN-LAST:event_fieldUnameFocusLost

    private void fieldpersonPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldpersonPhoneFocusLost
        // TODO add your handling code here:
         String name = fieldpersonPhone.getText();
        
        if(name.isEmpty()) {
            this.cvalidate = true;
        } else {
            this.cvalidate = false;
        }
    }//GEN-LAST:event_fieldpersonPhoneFocusLost

    private void fieldrecTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldrecTFocusLost
        // TODO add your handling code here:
         String name = fieldrecT.getText();
        
        if(name.isEmpty()) {
            this.dvalidate = true;
        } else {
            this.dvalidate = false;
        }
    }//GEN-LAST:event_fieldrecTFocusLost

    private void fieldnoSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldnoSFocusLost
        // TODO add your handling code here:
         String name = fieldnoS.getText();
        
        if(name.isEmpty()) {
            this.evalidate = true;
        } else {
            this.evalidate = false;
        }
    }//GEN-LAST:event_fieldnoSFocusLost

    private void fieldigFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldigFFocusLost
 String name = fieldigF.getText();
        
        if(name.isEmpty()) {
            this.fvalidate = true;
        } else {
            this.fvalidate = false;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fieldigFFocusLost

    private void fielddLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fielddLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fielddLActionPerformed

    private void fielddLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fielddLFocusLost
        // TODO add your handling code here:
         String name = fielddL.getText();
        
        if(name.isEmpty()) {
            this.gvalidate = true;
        } else {
            this.gvalidate = false;
        }
    }//GEN-LAST:event_fielddLFocusLost

    private void fieldnoIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldnoIFocusLost
        // TODO add your handling code here:
         String name = fieldnoI.getText();
        
        if(name.isEmpty()) {
            this.hvalidate = true;
        } else {
            this.hvalidate = false;
        }
    }//GEN-LAST:event_fieldnoIFocusLost

    private void fieldcoFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldcoFFocusLost
        // TODO add your handling code here:
         String name = fieldcoF.getText();
        
        if(name.isEmpty()) {
            this.ivalidate = true;
        } else {
            this.ivalidate = false;
        }
    }//GEN-LAST:event_fieldcoFFocusLost

    private void fielddeSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fielddeSFocusLost
        // TODO add your handling code here:
         String name = fielddeS.getText();
        
        if(name.isEmpty()) {
            this.jvalidate = true;
        } else {
            this.jvalidate = false;
        }
    }//GEN-LAST:event_fielddeSFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldFname;
    private javax.swing.JTextField fieldLname;
    private javax.swing.JTextField fieldUname;
    private javax.swing.JTextField fieldcoF;
    private javax.swing.JTextField fielddL;
    private javax.swing.JTextField fielddeS;
    private javax.swing.JTextField fieldigF;
    private javax.swing.JTextField fieldnoI;
    private javax.swing.JTextField fieldnoS;
    private javax.swing.JTextField fieldpersonEmail;
    private javax.swing.JTextField fieldpersonPhone;
    private javax.swing.JTextField fieldrecT;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JTextField recipePath;
    private javax.swing.JButton saveProductbtn;
    // End of variables declaration//GEN-END:variables
}
