/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab_cao2;
import Model.Person;
import Model.Contact;
import Model.Recipe;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author caofei
 */
public class EditJPanel extends javax.swing.JPanel {
    private Contact delPackage;
    private Recipe recipeViewed;


    /**
     * Creates new form EditJPanel
     */
    public EditJPanel() {
        initComponents();
    }
    EditJPanel(Contact deliveryPackage) {
        initComponents();
        this.delPackage = deliveryPackage;
        displayProductList();      
        displayPackageDetails();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();
        btnShow = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonBrowseImage = new javax.swing.JButton();
        fieldFname = new javax.swing.JTextField();
        fieldLname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldUname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fielddeS = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fieldrecT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldnoS = new javax.swing.JTextField();
        fieldigF = new javax.swing.JTextField();
        fielddL = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fieldnoI = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fieldcoF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fieldpersonPhone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fieldpersonEmail = new javax.swing.JTextField();
        recipePath = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 255, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 90, 20));

        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });
        add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, 30));

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 30));

        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 150, 30));
        add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 150, 160));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel20.setText("Picture");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jButtonBrowseImage.setText("Browser");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        add(jButtonBrowseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        fieldFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldFnameFocusLost(evt);
            }
        });
        add(fieldFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, -1));
        add(fieldLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, -1));

        jLabel8.setText("Username - Unique");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));
        add(fieldUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));

        jLabel9.setText("Chef’s First Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        jLabel10.setText("Chef’s Last Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));
        add(fielddeS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 100, -1));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel17.setText("Recipe ");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));
        add(fieldrecT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 90, -1));

        jLabel11.setText("Recipe title");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel12.setText("No. of Servings");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));
        add(fieldnoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 90, -1));
        add(fieldigF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 90, -1));
        add(fielddL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 90, -1));

        jLabel13.setText("Is Gluten Free ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabel14.setText("Difficulty level ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel15.setText("No. of Ingredients");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        fieldnoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnoIActionPerformed(evt);
            }
        });
        add(fieldnoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 100, -1));

        jLabel16.setText("Category of food");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));
        add(fieldcoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 100, -1));

        jLabel18.setText("Description");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));
        add(fieldpersonPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 100, -1));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel19.setText("Contact");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel21.setText("person phone");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel22.setText("person email");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));
        add(fieldpersonEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 100, -1));
        add(recipePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 593, -1, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        
        String phone=fieldpersonPhone.getText();
        String email=fieldpersonEmail.getText();

        String fName=fieldFname.getText();
        String lName=fieldLname.getText();
        String nName=fieldUname.getText();

       
        this.delPackage.setPhoneNumber(Long.valueOf(phone));
        this.delPackage.setEmailID(email);

        Person customer = this.delPackage.getCustomer();
        
        customer.setfName(fName);
        customer.setlName(lName);
        customer.setuName(nName);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:

        fieldrecT.setEnabled(false);

        String pid = (String) productComboBox.getSelectedItem();//pid赋值为所选择的
        Recipe prod = this.delPackage.findRecipe(pid);
        this.recipeViewed = prod;
        if (!prod.equals(null)) {
            
            fieldrecT.setText(prod.getRecT());
            fieldnoS.setText(String.valueOf(prod.getNoS()));
            fieldigF.setText(prod.getIgF());
            fielddL.setText(String.valueOf(prod.getdL()));
            fieldnoI.setText(String.valueOf(prod.getNoI()));
            fieldcoF.setText(prod.getCoF());
            fielddeS.setText(prod.getDeS());

        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // TODO add your handling code here:

       
        this.recipeViewed.setCoF(fieldcoF.getText());
        this.recipeViewed.setDeS(fielddeS.getText());
        this.recipeViewed.setIgF(fieldigF.getText());
        this.recipeViewed.setNoI(Integer.valueOf(fieldnoI.getText()));
        this.recipeViewed.setNoS(Float.valueOf(fieldnoS.getText()));
        this.recipeViewed.setRecT(fieldrecT.getText());
        this.recipeViewed.setdL(Double.valueOf(fielddL.getText()));
        

    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile=new JFileChooser();

        FileNameExtensionFilter fnef=new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue=browseImageFile.showOpenDialog(null);

        if(showOpenDialogue==JFileChooser.APPROVE_OPTION){
            File selectedImageFile=browseImageFile.getSelectedFile();
            String selectedImagePath=selectedImageFile.getAbsolutePath();
            recipePath.setText(selectedImagePath);

            ImageIcon ii=new ImageIcon(selectedImagePath);
            Image image=ii.getImage().getScaledInstance(jLabelImage.getWidth(),jLabelImage.getHeight(),Image.SCALE_SMOOTH);
            jLabelImage.setIcon(new ImageIcon(image));

        }
    }//GEN-LAST:event_jButtonBrowseImageActionPerformed

    private void fieldnoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnoIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldnoIActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void fieldFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFnameFocusLost
public void displayProductList() {

        for (Recipe p : this.delPackage.getProductList()) {
            productComboBox.addItem(p.getRecT());
        }

    }

    public void displayPackageDetails() {
        fieldpersonPhone.setText(String.valueOf(this.delPackage.getPhoneNumber()));
        fieldpersonEmail.setText(String.valueOf(this.delPackage.getEmailID()));
        

        Person customer = this.delPackage.getCustomer();
        
        fieldFname.setText(customer.getfName());
        fieldLname.setText(customer.getlName());
        fieldUname.setText(customer.getuName());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JTextField fieldFname;
    private javax.swing.JTextField fieldLname;
    private javax.swing.JTextField fieldUname;
    private javax.swing.JTextField fieldcoF;
    private javax.swing.JTextField fielddL;
    private javax.swing.JTextField fielddeS;
    private javax.swing.JTextField fieldigF;
    private javax.swing.JTextField fieldnoI;
    private javax.swing.JTextField fieldnoS;
    private javax.swing.JTextField fieldpersonEmail;
    private javax.swing.JTextField fieldpersonPhone;
    private javax.swing.JTextField fieldrecT;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JTextField recipePath;
    // End of variables declaration//GEN-END:variables
}
