/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminPanels;

import Business.Branch;
import Business.Business;
import Employee.Librarian;
import Employee.Manager;
import Role.BranchAdminRole;
import Role.CustomerRole;
import Role.LibrarianRole;
import Role.Role;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caofei
 */
public class CreatJPanel extends javax.swing.JPanel {

    private Business business;
    private Branch branch;
    private UserAccount useraccount;
    private UserAccountDirectory userAccountDirectory;
    DefaultTableModel tableModel;

    public CreatJPanel() {
        initComponents();
    }
    public CreatJPanel(Business business, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.branch=branch;
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        
        populateDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        fieldBranch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BranchComboBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        experienceText = new javax.swing.JTextField();
        designationText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ManagerComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        assignAgentBtn = new javax.swing.JButton();
        LibrarianComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 296, -1, -1));
        add(fieldBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 40));

        jButton1.setText("ADD BRANCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 30));

        add(BranchComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 200, 40));

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 110, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("ADD ACCOUNT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 140, 30));

        add(RoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, 30));

        jLabel6.setText("Designation");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 30));
        add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 30));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        registerBtn.setText("REGISTER");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));
        add(experienceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 150, 30));
        add(designationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 150, 30));

        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("If role is manager or librarian,please input");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 340, 40));

        jLabel9.setText("Experience");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, 30));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 150, 30));

        jLabel10.setText("Role");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        add(ManagerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Library", "Manager", "Librarian"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 488, 420, 150));

        assignAgentBtn.setText("ASSIGN");
        assignAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignAgentBtnActionPerformed(evt);
            }
        });
        add(assignAgentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 140, -1));

        add(LibrarianComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        if (RoleComboBox.getSelectedItem().equals("customer")) {
            this.business.getTopLevelUserAccountDirectory().createUserAccount(usernameText.getText(), passwordText.getText(), new CustomerRole());
            this.business.getCustomerlist().createCustomer(this.business.getTopLevelUserAccountDirectory().findByUsername(usernameText.getText()).getAccountId(), nameText.getText());
        }
        if (RoleComboBox.getSelectedItem().equals("branch manager")) {
            if (fieldBranch.getText() != "") {
                this.branch.getBranchuseraccountDirectory().createUserAccount(usernameText.getText(), passwordText.getText(), new BranchAdminRole());
                this.branch.getEmployeeDirectory().createManager(this.branch.getBranchuseraccountDirectory().findByUsername(usernameText.getText()).getAccountId(), nameText.getText(), experienceText.getText(), designationText.getText());
                populateDp2();
                populateDp3();
                
            } else {
                JOptionPane.showMessageDialog(null, "Create a new branch by filling the branch field to add it's branch manager.");
            }
        }
        if (RoleComboBox.getSelectedItem().equals("librarian")) {
            if (fieldBranch.getText() != "") {
                this.branch.getBranchuseraccountDirectory().createUserAccount(usernameText.getText(), passwordText.getText(), new LibrarianRole());
                this.branch.getEmployeeDirectory().createLibrarian(this.branch.getBranchuseraccountDirectory().findByUsername(usernameText.getText()).getAccountId(), nameText.getText(), experienceText.getText(), designationText.getText());
                populateDp2();
                populateDp3();
                
            } else {
                JOptionPane.showMessageDialog(null, "Create a new branch by filling the branch field to add it's branch manager.");
            }
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.branch = this.business.createBranch(fieldBranch.getText());
         populateDropdown1();
         populate();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void assignAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignAgentBtnActionPerformed
        // TODO add your handling code here:
        Manager m = (Manager) ManagerComboBox.getSelectedItem();
        Librarian l = (Librarian) LibrarianComboBox.getSelectedItem();

        int selectedRow = jTable1.getSelectedRow();

        Branch o = (Branch) jTable1.getValueAt(selectedRow, 0);
        o.setManager(m);
        o.setLibrarian(l);
        populate();
    }//GEN-LAST:event_assignAgentBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selectedIndex = BranchComboBox.getSelectedIndex();//选择的索引数字

        if (selectedIndex != -1) {
    
         String selectedValue = (String) BranchComboBox.getItemAt(selectedIndex);//获得索引的项目
         this.business.removeBranch(selectedValue);
         BranchComboBox.removeItemAt(selectedIndex);
        } 
        
        populateDropdown();
        populate();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void populateDropdown() {
        RoleComboBox.removeAllItems();
        for (String rolename : Role.getAllRoles()) {
            RoleComboBox.addItem(rolename);
        }
    }
    public void populateDropdown1() {
        BranchComboBox.removeAllItems();
        for (Branch n : business.getBranches()) {
            BranchComboBox.addItem(n.getName());
        }
    }
    public void populate() {

        tableModel.setRowCount(0);
        for (Branch o : this.business.getBranches()) {

            Object[] row = new Object[3];

            row[0] = o;
            row[1] = o.getManager();
            row[2] = o.getLibrarian();

            tableModel.addRow(row);
        }

    }
    
    
    public void populateDp2() {
        
        ManagerComboBox.removeAllItems();
        
        for(Manager m: this.branch.getEmployeeDirectory().getManagerList()) {
            ManagerComboBox.addItem(m);
        }
    }
    public void populateDp3() {
        
        LibrarianComboBox.removeAllItems();
        
        for(Librarian l: this.branch.getEmployeeDirectory().getLibrarianList()) {
            LibrarianComboBox.addItem(l);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BranchComboBox;
    private javax.swing.JComboBox LibrarianComboBox;
    private javax.swing.JComboBox ManagerComboBox;
    private javax.swing.JComboBox RoleComboBox;
    private javax.swing.JButton assignAgentBtn;
    private javax.swing.JTextField designationText;
    private javax.swing.JTextField experienceText;
    private javax.swing.JTextField fieldBranch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
